
variable "max_size" {}
variable "min_size" {}
variable "instance_type" {}
variable "component" {}
variable "env" {}
variable "subnets" {}
variable "app_port" {}
variable "vpc_id" {}
variable "server_app_port_sg_cidr" {}
variable "bastion_nodes" {}
variable "prometheus_nodes" {}
variable "vault_token" {}
variable "lb_ports" {}
variable "lb_app_port_sg_cidr" {}
variable "lb_type" {}
variable "lb_subnets" {}
variable "zone_id" {}
variable "certificate_arn" {}