format_version: 10
pipelines:
  expense-tf-apply:
    group: Terraform
    materials:
      git-da613e5:
        git: https://github.com/s-devops-i3/expense-terraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:PO+fKc/0ACBxMS8Orwcu7Q==:AZO6kTk6/symCNetdxq1i9Su0jgZMKZ7L5lNxjUUosM=
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: {command: terraform, arguments: [ "init", "-backend-config=dev-env/state.tfvars" ], run_if: passed}
                - exec: {command: terraform, arguments: [ "apply", "-var-file=dev-env/main.tfvars", "-auto-approve" ], run_if: passed}