format_version: 10
pipelines:
  expense-tf-destroy:
    group: Terraform
    materials:
      git-da613e5:
        git: https://github.com/s-devops-i3/expense-terraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:tMa6doi5yndKRc+n2T/SiQ==:XGTDT/yZ25RZ3ORgbR1ktGSIRualXzy2eRg66E19T4U=
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            terraform-apply:
              tasks:
                - exec: {command: terraform, arguments: [ "init", "-backend-config=dev-env/state.tfvars" ], run_if: passed}
                - exec: {command: terraform, arguments: [ "destroy", "-auto-approve" ], run_if: passed}
